//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package  {
	import org.flixel.*;
	
	public class MapSR_Playground extends MapBase {
		//Media content declarations
		[Embed(source="../data/temp/MapCSV_SR_Playground_Collision.txt", mimeType="application/octet-stream")] public var CSV_Collision:Class;
		[Embed(source="../data/temp/tiles_new_small_strip.png")] public var Img_Collision:Class;
		[Embed(source="../data/temp/MapCSV_SR_Playground_Obstacles.txt", mimeType="application/octet-stream")] public var CSV_Obstacles:Class;
		[Embed(source="../data/temp/tiles_new_small_strip.png")] public var Img_Obstacles:Class;

		
		public function MapSR_Playground() {

			_setCustomValues();

			bgColor = 0xff000000;

			layerCollision = new FlxTilemap();
			layerCollision.loadMap(new CSV_Collision, Img_Collision, 16);
			layerCollision.collideIndex = 3;
			layerCollision.drawIndex = 1;
			layerCollision.x = 0;
			layerCollision.y = 0;
			layerCollision.scrollFactor.x = 1.000000;
			layerCollision.scrollFactor.y = 1.000000;
			
			layerObstacles = new FlxTilemap();
			layerObstacles.loadMap(new CSV_Obstacles, Img_Obstacles, 16);
			layerObstacles.collideIndex = 3;
			layerObstacles.drawIndex = 1;			
			layerObstacles.x = 0;
			layerObstacles.y = 0;
			layerObstacles.scrollFactor.x = 1.000000;
			layerObstacles.scrollFactor.y = 1.000000;

			allLayers = [ layerCollision, layerObstacles ];

			mainLayer = layerCollision;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 1600;
			boundsMaxY = 800;
		}

		override public function addSpritesToLayerObstacles(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new Obstacle(1248, 304);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(816, 512);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(608, 512);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(1296, 576);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(1296, 768);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(784, 768);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(528, 736);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(448, 736);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
