//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package cas.spdr.map {
	import cas.spdr.gfx.sprite.BoostSection;
	import cas.spdr.gfx.sprite.FinishTrigger;
	import cas.spdr.gfx.sprite.Obstacle;
	import cas.spdr.gfx.sprite.Pickup;
	import cas.spdr.gfx.sprite.PlayerStart;
	import cas.spdr.gfx.sprite.Trigger;
	import cas.spdr.actor.FallingBlock;
	
	import org.flixel.*;
	import org.flixel.fefranca.FlxTilemapSloped;
	
	public class MapBoss1 extends MapBase {
		//Media content declarations
		[Embed(source="../../../../data/maps/B1. Boss1/MapCSV_Boss1_FG.txt", mimeType="application/octet-stream")] public var CSV_FG:Class;
		[Embed(source="../../../../data/temp/tiles_foreground.png")] public var Img_FG:Class;
		[Embed(source="../../../../data/maps/B1. Boss1/MapCSV_Boss1_Main.txt", mimeType="application/octet-stream")] public var CSV_Main:Class;
		[Embed(source="../../../../data/temp/tiles_black_37.png")] public var Img_Main:Class;
		[Embed(source="../../../../data/maps/B1. Boss1/MapCSV_Boss1_BG.txt", mimeType="application/octet-stream")] public var CSV_BG:Class;
		[Embed(source="../../../../data/temp/tiles_background.png")] public var Img_BG:Class;

		
		public function MapBoss1() {

			_setCustomValues();

			bgColor = 0xff2e5392;

			layerFG = new FlxTilemap();			
			layerFG.loadMap(new CSV_FG, Img_FG, 16);
			layerFG.collideIndex = 31;
			layerFG.drawIndex = 1;
			layerFG.x = 0;
			layerFG.y = 0;
			layerFG.scrollFactor.x = 1.500000;
			layerFG.scrollFactor.y = 1.000000;
			
			layerMain = new FlxTilemapSloped();
			layerMain.loadMap(new CSV_Main, Img_Main, 16);
			layerMain.collideIndex = 31;
			layerMain.drawIndex = 1;
			layerMain.x = 0;
			layerMain.y = 0;
			layerMain.scrollFactor.x = 1.000000;
			layerMain.scrollFactor.y = 1.000000;
			
			layerBG = new FlxTilemap();
			layerBG.loadMap(new CSV_BG, Img_BG, 16);
			layerBG.collideIndex = 31;
			layerBG.drawIndex = 1;
			layerBG.x = 0;
			layerBG.y = 0;
			layerBG.scrollFactor.x = 0.500000;
			layerBG.scrollFactor.y = 1.000000;

			allLayers = [ layerFG, layerMain, layerBG ];

			mainLayer = layerMain;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 9600;
			boundsMaxY = 1600;
		}

		override public function addSpritesToLayerMain(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new PlayerStart(72, 1032);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FinishTrigger(9448, 1496 -4);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(200, 1032);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(312, 1032);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(3032 +8, 1032 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(3160 +8, 1032 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(600 +8, 1080 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(728 +8, 1080 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(2904 +8, 1032 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(2744, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(2808, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(2872, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(2936, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(3000, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(3064, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(3128, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(3192, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(2680, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(3256, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(312, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(200, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(856 +8, 1080 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 4;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(984 +8, 1080 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 5;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(536, 1032);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 5;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(536, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 5;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(424, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 4;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(424, 1032);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 4;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(72 +8, 408 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(328 +8, 296 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(728 +8, 104 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1288 +8, 8 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(3896 +8, 840 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 21;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(4008 +8, 536 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 21;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(3288, 1304);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 21;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(3288, 1224);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 21;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4088, 1048);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 22;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4088, 1144);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 22;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4088, 1240);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 22;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4088, 1336);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 22;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4088, 1432);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 22;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(4344 +8, 328 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 22;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(4680 +8, 552 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 22;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(5128 +8, 296 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(5592 +8, 72 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4984, 984);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4984, 1064);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4984, 1144);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4984, 1224);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4984, 1304);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4984, 1384);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(4984, 1464);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 23;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(5768, 792);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(5768, 872);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(5768, 952);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(5768, 1032);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(5768, 1112);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(5768, 712);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(6040 +8, 536 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(6232 +8, 200 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(6760 +8, 24 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 24;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(7832 +8, 168 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 25;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(7176 +8, 104 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 25;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(7960 +8, 168 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 26;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(8744 +8, 168 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 26;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 636);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 636);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 668);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 668);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 700);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 700);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 732);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 732);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 764);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 764);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 988);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 1020);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 1052);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7980, 1116);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 988);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 1020);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 1052);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(7948, 1116);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(9020, 668);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(9052, 668);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(9084, 668);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(9128, 680);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1110;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(9176, 680);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1110;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(9128, 936);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1111;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(9176, 936);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1111;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(9128, 1240);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1112;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(9176, 1240);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1112;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(9064 +8, 1384 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1112;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(9064 +8, 824 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1110;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(9080 +8, 856 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1110;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(9096 +8, 1416 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1112;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(9112 +8, 1144 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1111;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(9144 +8, 1112 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1111;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
