//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package cas.spdr.map {
	import cas.spdr.gfx.sprite.BoostSection;
	import cas.spdr.gfx.sprite.FinishTrigger;
	import cas.spdr.gfx.sprite.Obstacle;
	import cas.spdr.gfx.sprite.Pickup;
	import cas.spdr.gfx.sprite.PlayerStart;
	
	import org.flixel.*;
	import org.flixel.fefranca.FlxTilemapSloped;
	
	public class MapTheLion extends MapBase {
		//Media content declarations
		[Embed(source="../../../../data/maps/1.TheLion/MapCSV_TheLion_FG.txt", mimeType="application/octet-stream")] public var CSV_FG:Class;
		[Embed(source="../../../../data/temp/tiles_foreground.png")] public var Img_FG:Class;
		[Embed(source="../../../../data/maps/1.TheLion/MapCSV_TheLion_Main.txt", mimeType="application/octet-stream")] public var CSV_Main:Class;
		[Embed(source="../../../../data/temp/tiles_black_37.png")] public var Img_Main:Class;
		[Embed(source="../../../../data/maps/1.TheLion/MapCSV_TheLion_BG.txt", mimeType="application/octet-stream")] public var CSV_BG:Class;
		[Embed(source="../../../../data/temp/tiles_background.png")] public var Img_BG:Class;

		
		public function MapTheLion() {

			_setCustomValues();

			bgColor = 0xff2e5392;

			layerFG = new FlxTilemap();			
			layerFG.loadMap(new CSV_FG, Img_FG, 16);
			layerFG.collideIndex = 31;
			layerFG.drawIndex = 1;
			layerFG.x = 0;
			layerFG.y = 0;
			layerFG.scrollFactor.x = 1.500000;
			layerFG.scrollFactor.y = 1.000000;
			
			layerMain = new FlxTilemapSloped();
			layerMain.loadMap(new CSV_Main, Img_Main, 16);
			layerMain.collideIndex = 31;
			layerMain.drawIndex = 1;
			layerMain.x = 0;
			layerMain.y = 0;
			layerMain.scrollFactor.x = 1.000000;
			layerMain.scrollFactor.y = 1.000000;
			
			layerBG = new FlxTilemap();
			layerBG.loadMap(new CSV_BG, Img_BG, 16);
			layerBG.collideIndex = 31;
			layerBG.drawIndex = 1;
			layerBG.x = 0;
			layerBG.y = 0;
			layerBG.scrollFactor.x = 0.500000;
			layerBG.scrollFactor.y = 1.000000;

			allLayers = [ layerFG, layerMain, layerBG ];

			mainLayer = layerMain;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 6400;
			boundsMaxY = 1600;
		}

		override public function addSpritesToLayerMain(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new PlayerStart(72, 1000);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FinishTrigger(6136, 1016 -4);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(428, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(460, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(492, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(524, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(556, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(2220, 1068);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(588, 1084);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new BoostSection(3176, 1023-1);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Obstacle(2604, 1052);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new BoostSection(5192, 943-1);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(208, 592);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(176, 592);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(144, 592);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(144, 560);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(176, 560);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(208, 560);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(416, 976);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(480, 960);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(560, 960);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(624, 976);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(1344, 992);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(1424, 960);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(1504, 960);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(2000, 960);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(2064, 928);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(2128, 928);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(3984, 1008);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(4032, 976);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(4096, 960);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "bronze";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(5040, 848);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(5088, 880);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(5136, 912);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(2496, 848);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(2560, 864);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(2624, 896);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(848, 896);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(880, 864);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(912, 832);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "silver";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
