//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package cas.spdr.map {
	import cas.spdr.gfx.sprite.BoostSection;
	import cas.spdr.gfx.sprite.FinishTrigger;
	import cas.spdr.gfx.sprite.Obstacle;
	import cas.spdr.gfx.sprite.Pickup;
	import cas.spdr.gfx.sprite.PlayerStart;
	import cas.spdr.gfx.sprite.Trigger;
	import cas.spdr.actor.FallingBlock;
	
	import org.flixel.*;
	import org.flixel.fefranca.FlxTilemapSloped;
	
	public class MapBoss2 extends MapBase {
		//Media content declarations
		[Embed(source="../../../../data/maps/B2. Boss2/MapCSV_Boss2_FG.txt", mimeType="application/octet-stream")] public var CSV_FG:Class;
		[Embed(source="../../../../data/temp/tiles_foreground.png")] public var Img_FG:Class;
		[Embed(source="../../../../data/maps/B2. Boss2/MapCSV_Boss2_Main.txt", mimeType="application/octet-stream")] public var CSV_Main:Class;
		[Embed(source="../../../../data/temp/tiles_black_37.png")] public var Img_Main:Class;
		[Embed(source="../../../../data/maps/B2. Boss2/MapCSV_Boss2_BG.txt", mimeType="application/octet-stream")] public var CSV_BG:Class;
		[Embed(source="../../../../data/temp/tiles_background.png")] public var Img_BG:Class;

		
		public function MapBoss2() {

			_setCustomValues();

			bgColor = 0xff2e5392;

			layerFG = new FlxTilemap();			
			layerFG.loadMap(new CSV_FG, Img_FG, 16);
			layerFG.collideIndex = 31;
			layerFG.drawIndex = 1;
			layerFG.x = 0;
			layerFG.y = 0;
			layerFG.scrollFactor.x = 1.500000;
			layerFG.scrollFactor.y = 1.000000;
			
			layerMain = new FlxTilemapSloped();
			layerMain.loadMap(new CSV_Main, Img_Main, 16);
			layerMain.collideIndex = 31;
			layerMain.drawIndex = 1;
			layerMain.x = 0;
			layerMain.y = 0;
			layerMain.scrollFactor.x = 1.000000;
			layerMain.scrollFactor.y = 1.000000;
			
			layerBG = new FlxTilemap();
			layerBG.loadMap(new CSV_BG, Img_BG, 16);
			layerBG.collideIndex = 31;
			layerBG.drawIndex = 1;
			layerBG.x = 0;
			layerBG.y = 0;
			layerBG.scrollFactor.x = 0.500000;
			layerBG.scrollFactor.y = 1.000000;

			allLayers = [ layerFG, layerMain, layerBG ];

			mainLayer = layerMain;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 5200;
			boundsMaxY = 4800;
		}

		override public function addSpritesToLayerMain(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new FinishTrigger(6136, 1016 -4);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(5232, 592);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Pickup(5296, 608);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["colorVal"] = "gold";
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new PlayerStart(712, 3912);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(888, 3336);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(472 +8, 3016 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1256 +8, 2936 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(760, 3000);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(1320, 2680);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(1320, 2504);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 4;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(984 +8, 2424 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 4;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1432 +8, 2424 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1064 +8, 1976 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 5;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(792, 2072);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 5;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(552, 1832);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 6;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(632, 1832);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 6;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(456, 1832);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 6;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(392, 2104);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 6;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(296 +8, 1912 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 6;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1112 +8, 1272 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 9;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(824, 1192);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 9;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(824, 1112);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 9;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(824, 1032);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 9;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(408, 1272);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 7;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(408, 1352);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 7;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(408, 1432);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 7;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(520, 1208);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 8;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(520, 1128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 8;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(632, 3528);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 10;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(856 +8, 3592 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 10;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(680 +8, 2232 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 11;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Trigger(936, 2152);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 11;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(536 +8, 2472 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 10;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(840 +8, 2600 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(936 +8, 1640 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 4;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(280 +8, 3016 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1240 +8, 3400 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1368 +8, 3400 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1128 +8, 2648 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(856 +8, 1272 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 7;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(984 +8, 1272 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 7;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(728 +8, 1272 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 8;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(600 +8, 1272 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 8;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FallingBlock(1240 +8, 1272 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["triggerId"] = 8;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new FinishTrigger(1880, 1224 -4);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
