//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package  {
	import org.flixel.*;
	import org.flixel.fefranca.FlxTilemapSloped;
	
	public class MapMainMenu extends MapBase {
		//Media content declarations
		[Embed(source="../data/maps/MapCSV_MainMenu_FG.txt", mimeType="application/octet-stream")] public var CSV_FG:Class;
		[Embed(source="../data/temp/tiles_foreground.png")] public var Img_FG:Class;
		[Embed(source="../data/maps/MapCSV_MainMenu_Main.txt", mimeType="application/octet-stream")] public var CSV_Main:Class;
		[Embed(source="../data/temp/tiles_black_37.png")] public var Img_Main:Class;
		[Embed(source="../data/maps/MapCSV_MainMenu_BG.txt", mimeType="application/octet-stream")] public var CSV_BG:Class;
		[Embed(source="../data/temp/tiles_background.png")] public var Img_BG:Class;

		
		public function MapMainMenu() {

			_setCustomValues();

			bgColor = 0xff2e5392;

			layerFG = new FlxTilemap();			
			layerFG.loadMap(new CSV_FG, Img_FG, 16);
			layerFG.collideIndex = 31;
			layerFG.drawIndex = 1;
			layerFG.x = 0;
			layerFG.y = 0;
			layerFG.scrollFactor.x = 1.500000;
			layerFG.scrollFactor.y = 1.000000;
			
			layerMain = new FlxTilemapSloped();
			layerMain.loadMap(new CSV_Main, Img_Main, 16);
			layerMain.collideIndex = 31;
			layerMain.drawIndex = 1;
			layerMain.x = 0;
			layerMain.y = 0;
			layerMain.scrollFactor.x = 1.000000;
			layerMain.scrollFactor.y = 1.000000;
			
			layerBG = new FlxTilemap();
			layerBG.loadMap(new CSV_BG, Img_BG, 16);
			layerBG.collideIndex = 31;
			layerBG.drawIndex = 1;
			layerBG.x = 0;
			layerBG.y = 0;
			layerBG.scrollFactor.x = 0.500000;
			layerBG.scrollFactor.y = 1.000000;

			allLayers = [ layerFG, layerMain, layerBG ];

			mainLayer = layerMain;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 3680;
			boundsMaxY = 1600;
		}

		override public function addSpritesToLayerMain(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new PlayerStart(68, 1282);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Door(312, 1288+8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["levelId"] = 1;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Door(1080, 1272+8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["levelId"] = 2;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new Door(696, 1048 +8);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj["levelId"] = 3;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
